---
- hosts: all
  become: true
  tasks:
    - include: dependencies.yaml

    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10"  --node-name k8s-master --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Setup kubeconfig for vagrant user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/vagrant/.kube
        - cp /etc/kubernetes/admin.conf /home/vagrant/.kube/config
        - chown vagrant:vagrant /home/vagrant/.kube/config
      args:
        creates: /home/vagrant/.kube/config

    # - name: Install flannel pod network
    #   become: vagrant
    #   command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml

    # - name: Generate join command
    #   command: kubeadm token create --print-join-command
    #   register: join_command
  
    # - name: Copy join command to local file
    #   local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

    